spring.application.name=java_backend

# AWS RDS PostgreSQL Cloud Connection
spring.datasource.url=jdbc:postgresql://smartnotes-postgres-db.cfoamiu4acf8.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MakeThings916^_^

# Hibernate Table Generation Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Log SQL queries to console for debugging
spring.jpa.show-sql=true

# AWS S3 Configuration
aws.s3.bucket-name=andy-smartnotes-storage-test
aws.s3.region=us-east-2
# Safe environment variable lookups for Spring Boot
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}